
SRC = correction.cpp

debug:

	g++ $(FLAGS) $(FLAGS_SHARED) $(FLAGS_DEBUG) $(LIB) $(INCLUDE) $(SRC) -o $(OUTPUT_FNAME)

release:

	g++ $(FLAGS) $(FLAGS_SHARED) $(FLAGS_RELEASE) $(LIB) $(INCLUDE) $(SRC) -o $(OUTPUT_FNAME)

